// This file is auto-generated by TanStack Router
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { createFileRoute } from '@tanstack/react-router';

// Create Virtual Routes

const UsersLazyImport = createFileRoute('/users')();
const BatchesLazyImport = createFileRoute('/batches')();
const IndexLazyImport = createFileRoute('/')();

// Create/Update Routes

const UsersLazyRoute = UsersLazyImport.update({
  path: '/users',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users.lazy').then((d) => d.Route));

const BatchesLazyRoute = BatchesLazyImport.update({
  path: '/batches',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/batches.lazy').then((d) => d.Route));

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/batches': {
      preLoaderRoute: typeof BatchesLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/users': {
      preLoaderRoute: typeof UsersLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([IndexLazyRoute, BatchesLazyRoute, UsersLazyRoute]);
